### ISSUE TITLE
Deprecation warning 調整

### ISSUE THREAD

**Issue by smlsunxie** [trunk-studio/cargocms#1116]
進後台 user 管理

url: http://localhost:5001/admin#/admin/user

出現下面 Deprecation warning

```
Deprecation warning: value provided is not in a recognized ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments:
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: %%, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.createFromInputFallback (/Users/spooky/projects/trunk/cargocms/node_modules/moment/moment.js:309:98)
    at configFromString (/Users/spooky/projects/trunk/cargocms/node_modules/moment/moment.js:2048:32)
    at configFromInput (/Users/spooky/projects/trunk/cargocms/node_modules/moment/moment.js:2408:13)
    at prepareConfig (/Users/spooky/projects/trunk/cargocms/node_modules/moment/moment.js:2391:13)
    at createFromConfig (/Users/spooky/projects/trunk/cargocms/node_modules/moment/moment.js:2358:44)
    at createLocalOrUTC (/Users/spooky/projects/trunk/cargocms/node_modules/moment/moment.js:2445:16)
    at local__createLocal (/Users/spooky/projects/trunk/cargocms/node_modules/moment/moment.js:2449:16)
    at utils_hooks__hooks (/Users/spooky/projects/trunk/cargocms/node_modules/moment/moment.js:16:29)
    at [object Object].DATE.$applyTimezone (/Users/spooky/projects/trunk/cargocms/node_modules/sequelize/lib/data-types.js:473:14)
    at [object Object].DATE.$stringify (/Users/spooky/projects/trunk/cargocms/node_modules/sequelize/lib/dialects/mysql/data-types.js:34:37)
    at [object Object].ABSTRACT.stringify (/Users/spooky/projects/trunk/cargocms/node_modules/sequelize/lib/data-types.js:77:17)
    at Object.QueryGenerator.escape (/Users/spooky/projects/trunk/cargocms/node_modules/sequelize/lib/dialects/abstract/query-generator.js:968:32)
    at Object.QueryGenerator.whereItemQuery (/Users/spooky/projects/trunk/cargocms/node_modules/sequelize/lib/dialects/abstract/query-generator.js:2349:22)
```

**Comment by dd-han** [comment]
同 #743
