### ISSUE TITLE
對別人的私人香水做感覺回饋，會 ERR 500

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#1136]
![2016-11-30 14-05-08](https://cloud.githubusercontent.com/assets/5909203/20741685/d6949176-b706-11e6-8d1a-9b9ab0ecc3f0.png)

錯誤如下（前端收的到）：
```
"TypeError: Cannot convert undefined or null to object
    at _callee11$ (/home/cargo/labfnp/api/controllers/api/labfnp/RecipeController.js:235:7)
    at tryCatch (/home/cargo/labfnp/node_modules/regenerator-runtime/runtime.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/cargo/labfnp/node_modules/regenerator-runtime/runtime.js:337:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/cargo/labfnp/node_modules/regenerator-runtime/runtime.js:96:21)
    at tryCatch (/home/cargo/labfnp/node_modules/regenerator-runtime/runtime.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/home/cargo/labfnp/node_modules/regenerator-runtime/runtime.js:279:24)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/home/cargo/labfnp/node_modules/regenerator-runtime/runtime.js:96:21)
    at step (/home/cargo/labfnp/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/cargo/labfnp/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at propagateAslWrapper (/home/cargo/labfnp/node_modules/async-listener/index.js:421:23)
    at /home/cargo/labfnp/node_modules/async-listener/index.js:458:70
    at wrapped (/home/cargo/labfnp/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at wrappedPromise.linkTransaction (/home/cargo/labfnp/node_modules/newrelic/lib/instrumentation/promise.js:273:65)
    at wrappedPromise.wrapped [as __NR_wrapper] (/home/cargo/labfnp/node_modules/newrelic/lib/transaction/tracer/index.js:183:28)
    at __NR_wrappedThenHandler (/home/cargo/labfnp/node_modules/newrelic/lib/instrumentation/promise.js:445:26)"
```

**Comment by dd-han** [comment]
另外雖然出現錯誤，但是實際上有新增進去
