### ISSUE TITLE
sequelize 與 node 6.9.2 的相容性問題

### ISSUE THREAD

**Issue by dd-han** [trunk-studio/cargocms#1265]
用 6.9.2 跑下面的 Spec ，admin 使用者會等到 timeout 才進去DB：

https://github.com/trunk-studio/cargocms/blame/feature/b2bSpec/test/unit/controllers/api/OrderController.spec.js#L4

同時終端機會有以下錯誤：
```
2016-12-28 15:01:15.40 <debug> lift.js:82 (_printSuccessMsg) -------------------------------------------------------
  about Order controllers
Unhandled rejection SequelizeDatabaseError: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
    at Query.formatError (/home/dd-han/projects/cargocms/node_modules/sequelize/lib/dialects/mysql/query.js:175:14)
    at Query._callback (/home/dd-han/projects/cargocms/node_modules/sequelize/lib/dialects/mysql/query.js:49:21)
    at Query.Sequence.end (/home/dd-han/projects/cargocms/node_modules/mysql/lib/protocol/sequences/Sequence.js:86:24)
    at Query.ErrorPacket (/home/dd-han/projects/cargocms/node_modules/mysql/lib/protocol/sequences/Query.js:94:8)
    at Protocol._parsePacket (/home/dd-han/projects/cargocms/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/dd-han/projects/cargocms/node_modules/mysql/lib/protocol/Parser.js:74:12)
    at Protocol.write (/home/dd-han/projects/cargocms/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/dd-han/projects/cargocms/node_modules/mysql/lib/Connection.js:109:28)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread [as _originalOnread] (net.js:548:20)
    at TCP.onread (/home/dd-han/projects/cargocms/node_modules/async-listener/glue.js:188:31)

    1) "before all" hook
(node:23651) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: AuthService.getSessionUser.restore is not a function
```

並且 npm 會卡住不會自動結束，將 node 降級至 6.3.1 後。有懷疑是 Lock 問題用以下指令 dorp 整個資料表：
`drop DATABASE cargo; create DATABASE cargo;`

不過就算是全新的資料表，跑上面的 spec 還是會出現一樣的錯誤 + 卡住。

**Comment by dd-han** [comment]
目前看起來 `test/util/adminAuthHelper.js` 的 `User.findOrCreate` 會卡住

但是 spec 裡面的 `User.create` 就沒有問題
